title:              "스마일 다이어리"
tagline:            "스타트업 1인 디지털 마케터의 이야기"
email:              "junian9193@gmail.com"
description:        "비전공 행정학과 학생이 디지털 마케터로 취업하고 스타트업의 1인 마케터로 살아온 이야기"
author:             "주니언"
baseurl:            "/"
url:                "https://heejun.kim"
locale:             "ko_KR"
thumbnail:          "/img/blog_thumbnail.jpg" #블로그 썸네일

# Social Profiles


# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-paginate

disqus:
  shortname: smilediary
